package com.byonix.shoplink.domain.enums;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    REGISTER_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFIED,
    NEW_DEVICE_LOGIN,
    SUSPICIOUS_LOGIN,
    ADMIN_LOGIN_FAILED,
    ADMIN_LOGIN_SUCCESS,
    REFRESH_TOKEN_REUSE_DETECTED,
    LOGOUT_ALL,
    IP_BLOCKED,
    MFA_SUCCESS,
    MFA_FAILED
}
