package com.byonix.shoplink.domain.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * POS-24: one cashier operating one till's drawer for a bounded period. The id is generated by the
 * till (a shift can be opened offline and sales name it before it reaches the server). See V41.
 *
 * Financial totals are not stored as truth here: {@code expectedCash}/{@code variance} are the
 * server's figures at the moment the close arrived, next to what the till reported, and the live
 * figures are always recomputed from the linked records (PosShiftService).
 */
@Getter
@Setter
@Entity
@Table(name = "pos_shifts")
public class PosShift implements org.springframework.data.domain.Persistable<UUID> {
    public enum Status { OPEN, CLOSED, CLOSED_WITH_VARIANCE, FORCE_CLOSED }

    @Id
    private UUID id;

    @Column(name = "store_id", nullable = false)
    private UUID storeId;

    @Column(name = "device_id")
    private UUID deviceId;

    @Column(name = "shift_number", nullable = false, length = 40)
    private String shiftNumber;

    @Column(name = "cashier_id")
    private UUID cashierId;

    @Column(name = "cashier_name", nullable = false, length = 160)
    private String cashierName;

    @Column(nullable = false, length = 3)
    private String currency;

    @Column(name = "opened_at", nullable = false)
    private Instant openedAt;

    @Column(name = "opening_cash", nullable = false, precision = 12, scale = 3)
    private BigDecimal openingCash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private Status status;

    @Column(name = "closed_at")
    private Instant closedAt;

    @Column(name = "closed_by_id")
    private UUID closedById;

    @Column(name = "closed_by_name", length = 160)
    private String closedByName;

    @Column(name = "counted_cash", precision = 12, scale = 3)
    private BigDecimal countedCash;

    @Column(name = "device_expected_cash", precision = 12, scale = 3)
    private BigDecimal deviceExpectedCash;

    @Column(name = "device_variance", precision = 12, scale = 3)
    private BigDecimal deviceVariance;

    @Column(name = "expected_cash", precision = 12, scale = 3)
    private BigDecimal expectedCash;

    @Column(precision = 12, scale = 3)
    private BigDecimal variance;

    @Column(name = "closing_manager_id")
    private UUID closingManagerId;

    @Column(name = "closing_manager_name", length = 160)
    private String closingManagerName;

    @Column(name = "close_note", length = 300)
    private String closeNote;

    @Column(name = "force_closed_by_id")
    private UUID forceClosedById;

    @Column(name = "force_closed_by_name", length = 160)
    private String forceClosedByName;

    @Column(name = "force_close_note", length = 300)
    private String forceCloseNote;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** The id comes from the till: a new shift must always be INSERTed (see PosSyncOperation). */
    @Transient
    private boolean fresh = true;

    @Override
    public boolean isNew() {
        return fresh;
    }

    @PostLoad
    @PostPersist
    void markStored() {
        fresh = false;
    }

    public boolean isOpen() {
        return status == Status.OPEN;
    }
}
