# Creates or updates a ShopLink admin user in PostgreSQL.
# Password hashing matches Spring Security BCryptPasswordEncoder(strength=12).
#
# Examples:
#   .\scripts\create-admin-user.ps1 -Email "admin@yourcompany.com" -Password "ChangeMe!12345"
#   .\scripts\create-admin-user.ps1 -Role SUPPORT_ADMIN -UseDockerCompose
#   .\scripts\create-admin-user.ps1 -DbHost "myserver.postgres.database.azure.com" -DbName shoplink_db `
#       -DbUser shoplink_user -DbPassword "secret" -SslMode require
#
# Notes:
#   - SUPER_ADMIN login requires MFA challenge when REQUIRE_SUPER_ADMIN_MFA=true (production default).
#     Use SUPPORT_ADMIN for first login without MFA, or complete MFA verify after SUPER_ADMIN login.
#   - Local dev: MFA verify code 000000 works only when expose-tokens-in-response=true.

param(
    [Parameter(Mandatory = $true)]
    [string] $Email,

    [Parameter(Mandatory = $true)]
    [string] $Password,

    [string] $FullName = "ShopLink Admin",

    [ValidateSet("SUPER_ADMIN", "SUPPORT_ADMIN", "FINANCE_ADMIN", "READ_ONLY_ADMIN")]
    [string] $Role = "SUPER_ADMIN",

    [switch] $Force,

    [switch] $UseDockerCompose,

    [string] $DbHost = $env:DB_HOST,
    [string] $DbPort = $(if ($env:DB_PORT) { $env:DB_PORT } else { "5432" }),
    [string] $DbName = $(if ($env:DB_NAME) { $env:DB_NAME } else { "shoplink_db" }),
    [string] $DbUser = $(if ($env:DB_USERNAME) { $env:DB_USERNAME } else { "shoplink_user" }),
    [string] $DbPassword = $env:DB_PASSWORD,
    [ValidateSet("", "require", "prefer", "disable")]
    [string] $SslMode = ""
)

$ErrorActionPreference = "Stop"

if (-not $DbHost) { $DbHost = "localhost" }
if (-not $DbPassword) {
    $secure = Read-Host "Database password ($DbUser@$DbHost)" -AsSecureString
    $DbPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
}

$emailNorm = $Email.Trim().ToLower()
$fullNameEsc = $FullName.Replace("'", "''")
$emailEsc = $emailNorm.Replace("'", "''")
$roleEsc = $Role.Replace("'", "''")

Write-Host "Generating BCrypt hash (cost 12)..." -ForegroundColor Cyan
$passwordB64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($Password))
$hash = docker run --rm -e "PWD_B64=$passwordB64" node:22-alpine sh -c @'
apk add --no-cache python3 py3-pip >/dev/null 2>&1
pip install --quiet bcrypt
python3 -c "
import os, base64, bcrypt
pwd = base64.b64decode(os.environ['PWD_B64']).decode('utf-8')
print(bcrypt.hashpw(pwd.encode('utf-8'), bcrypt.gensalt(rounds=12)).decode('utf-8'))
"
'@
if (-not $hash -or $hash -notmatch '^\$2[aby]\$') {
    throw "Failed to generate BCrypt hash. Is Docker running?"
}
$hashEsc = $hash.Trim().Replace("'", "''")

$mfaEnabled = if ($Role -eq "SUPER_ADMIN") { "FALSE" } else { "FALSE" }

$sql = @"
-- ShopLink bootstrap admin (generated by create-admin-user.ps1)
DO `$`$
DECLARE
    v_email TEXT := '$emailEsc';
    v_exists UUID;
BEGIN
    SELECT id INTO v_exists FROM app_users WHERE lower(email) = lower(v_email) LIMIT 1;

    IF v_exists IS NOT NULL AND NOT $($Force.IsPresent.ToString().ToLower()) THEN
        RAISE EXCEPTION 'User already exists: %. Re-run with -Force to update password and role.', v_email;
    END IF;

    IF v_exists IS NOT NULL THEN
        UPDATE app_users SET
            full_name = '$fullNameEsc',
            password_hash = '$hashEsc',
            role = '$roleEsc',
            is_active = TRUE,
            email_verified_at = COALESCE(email_verified_at, NOW()),
            password_changed_at = NOW(),
            failed_login_count = 0,
            locked_until = NULL,
            force_password_reset = FALSE,
            admin_unlock_required = FALSE,
            mfa_enabled = $mfaEnabled,
            updated_at = NOW()
        WHERE id = v_exists;
        RAISE NOTICE 'Updated admin user % (role=%)', v_email, '$roleEsc';
    ELSE
        INSERT INTO app_users (
            id, full_name, email, password_hash, role, is_active, token_version,
            email_verified_at, failed_login_count, mfa_enabled, force_password_reset,
            suspicious_activity_flag, admin_unlock_required, password_changed_at,
            created_at, updated_at
        ) VALUES (
            gen_random_uuid(), '$fullNameEsc', v_email, '$hashEsc', '$roleEsc', TRUE, 0,
            NOW(), 0, $mfaEnabled, FALSE, FALSE, FALSE, NOW(), NOW(), NOW()
        );
        RAISE NOTICE 'Created admin user % (role=%)', v_email, '$roleEsc';
    END IF;
END `$`$;
"@

$sqlFile = Join-Path $env:TEMP "shoplink-create-admin-$(Get-Random).sql"
Set-Content -Path $sqlFile -Value $sql -Encoding UTF8

try {
    if ($UseDockerCompose) {
        Write-Host "Running SQL via docker compose (postgres)..." -ForegroundColor Cyan
        Get-Content $sqlFile | docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U $DbUser -d $DbName
    }
    else {
        $env:PGPASSWORD = $DbPassword
        if ($SslMode) { $env:PGSSLMODE = $SslMode }
        elseif ($env:DB_URL_SUFFIX -match "sslmode=(\w+)") { $env:PGSSLMODE = $Matches[1] }
        Write-Host "Running SQL via psql ($DbUser@${DbHost}:$DbPort/$DbName)..." -ForegroundColor Cyan
        if (Get-Command psql -ErrorAction SilentlyContinue) {
            psql -h $DbHost -p $DbPort -U $DbUser -d $DbName -v ON_ERROR_STOP=1 -f $sqlFile
        }
        else {
            Get-Content $sqlFile | docker run --rm -i `
                -e PGPASSWORD=$DbPassword `
                -e PGSSLMODE=$env:PGSSLMODE `
                postgres:16 `
                psql -h $DbHost -p $DbPort -U $DbUser -d $DbName -v ON_ERROR_STOP=1
        }
    }
    Write-Host ""
    Write-Host "Done." -ForegroundColor Green
    Write-Host "  Email:    $emailNorm"
    Write-Host "  Role:     $Role"
    Write-Host "  Admin UI: POST /api/admin/auth/login"
    if ($Role -eq "SUPER_ADMIN") {
        Write-Host ""
        Write-Host "SUPER_ADMIN may require MFA at login. For first access without MFA setup, use:" -ForegroundColor Yellow
        Write-Host "  .\scripts\create-admin-user.ps1 ... -Role SUPPORT_ADMIN"
    }
}
finally {
    Remove-Item -Force $sqlFile -ErrorAction SilentlyContinue
    Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    Remove-Item Env:PGSSLMODE -ErrorAction SilentlyContinue
}
