-- POS-24: cashier shifts (one cashier on one till for a bounded period) and drawer cash movements.
-- Additive only; nothing existing is rewritten. Historical POS orders and returns keep a NULL shift.
--
-- A shift is opened, moved and closed at the till, possibly offline, and uploaded through the same
-- idempotency record as sales (pos_sync_operations; types SHIFT_OPEN / SHIFT_CASH_MOVEMENT /
-- SHIFT_CLOSE). Its id is generated by the till, so sales made offline can name it before it exists
-- here; the link is therefore a plain column (no foreign key) and every total is computed only from
-- rows of the shift's own store AND device, so a foreign id can never pull in another drawer.
--
-- No financial total is stored as truth: the drawer's expected cash is recomputed from the synced
-- orders, returns and movements (PosShiftService). What the till reported at close is kept beside the
-- server's own figure so a difference is visible, never silently overwritten.

CREATE TABLE pos_shifts (
    id UUID PRIMARY KEY,
    store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    -- The till whose drawer this is (kept if the device is later revoked or re-activated).
    device_id UUID REFERENCES pos_devices(id) ON DELETE SET NULL,
    shift_number VARCHAR(40) NOT NULL,
    cashier_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
    cashier_name VARCHAR(160) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    opening_cash NUMERIC(12, 3) NOT NULL CHECK (opening_cash >= 0),
    status VARCHAR(30) NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'CLOSED_WITH_VARIANCE', 'FORCE_CLOSED')),
    closed_at TIMESTAMP WITH TIME ZONE,
    closed_by_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
    closed_by_name VARCHAR(160),
    -- What the cashier counted in the drawer at close.
    counted_cash NUMERIC(12, 3) CHECK (counted_cash IS NULL OR counted_cash >= 0),
    -- The till's own figures at close (provisional: computed from what the till had, synced or not).
    device_expected_cash NUMERIC(12, 3),
    device_variance NUMERIC(12, 3),
    -- The server's figures when the close arrived (from the records synced by then).
    expected_cash NUMERIC(12, 3),
    variance NUMERIC(12, 3),
    closing_manager_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
    closing_manager_name VARCHAR(160),
    close_note VARCHAR(300),
    -- FORCE_CLOSED from the dashboard (the till never closed it, e.g. its data was lost).
    force_closed_by_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
    force_closed_by_name VARCHAR(160),
    force_close_note VARCHAR(300),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ux_pos_shifts_number UNIQUE (device_id, shift_number)
);
-- One drawer, one open shift: a till can never have two open shifts on the server.
CREATE UNIQUE INDEX ux_pos_shifts_one_open_per_device ON pos_shifts(device_id) WHERE status = 'OPEN';
CREATE INDEX ix_pos_shifts_store ON pos_shifts(store_id, opened_at DESC);

CREATE TABLE pos_shift_cash_movements (
    id UUID PRIMARY KEY,
    shift_id UUID NOT NULL REFERENCES pos_shifts(id) ON DELETE CASCADE,
    store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    device_id UUID REFERENCES pos_devices(id) ON DELETE SET NULL,
    operation_id UUID NOT NULL UNIQUE REFERENCES pos_sync_operations(operation_id) ON DELETE CASCADE,
    movement_type VARCHAR(10) NOT NULL CHECK (movement_type IN ('CASH_IN', 'CASH_OUT')),
    reason VARCHAR(30) NOT NULL CHECK (reason IN
        ('CHANGE_FLOAT', 'MANAGER_ADJUSTMENT', 'BANK_DEPOSIT', 'PETTY_CASH', 'SAFE_DROP', 'OTHER')),
    note VARCHAR(300),
    amount NUMERIC(12, 3) NOT NULL CHECK (amount > 0),
    staff_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
    staff_name VARCHAR(160) NOT NULL,
    manager_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
    manager_name VARCHAR(160),
    moved_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX ix_pos_shift_cash_movements_shift ON pos_shift_cash_movements(shift_id, moved_at);

-- Sales and returns name the shift they were rung up in (NULL = before POS-24, or shifts off).
ALTER TABLE customer_orders ADD COLUMN pos_shift_id UUID;
CREATE INDEX ix_customer_orders_pos_shift ON customer_orders(pos_shift_id) WHERE pos_shift_id IS NOT NULL;
ALTER TABLE pos_returns ADD COLUMN shift_id UUID;
CREATE INDEX ix_pos_returns_shift ON pos_returns(shift_id) WHERE shift_id IS NOT NULL;

-- Manager approvals of cash movements and of closing a shift go in the same audit table.
ALTER TABLE pos_manager_overrides ADD COLUMN shift_id UUID REFERENCES pos_shifts(id) ON DELETE CASCADE;
ALTER TABLE pos_manager_overrides ADD COLUMN cash_movement_id UUID REFERENCES pos_shift_cash_movements(id) ON DELETE CASCADE;

ALTER TABLE pos_sync_conflicts DROP CONSTRAINT ck_pos_sync_conflicts_type;
ALTER TABLE pos_sync_conflicts ADD CONSTRAINT ck_pos_sync_conflicts_type CHECK (conflict_type IN ('OVERSOLD', 'PRODUCT_DELETED',
    'PRODUCT_UNAVAILABLE', 'VARIANT_DELETED', 'VARIANT_UNAVAILABLE', 'PRODUCT_CHANGED', 'PRICE_CHANGED',
    'CUSTOMER_UNLINKED', 'DISCOUNT_CHANGED', 'DISCOUNT_LIMIT_REACHED', 'STAFF_UNAVAILABLE', 'OVERRIDE_UNVERIFIED',
    'RETURN_QUANTITY_EXCEEDED', 'RETURN_APPROVAL_MISSING', 'EXCHANGE_MISMATCH',
    'SHIFT_RECONCILIATION_MISMATCH', 'SHIFT_APPROVAL_MISSING'));
